import type { Metadata } from "next";
import type {ReactNode} from "react";
import '../styles/index.scss';
import {ResponseProvider} from "@Providers/response.provider";
import {UserInfoProvider} from "@Providers/userInfo.provider";
import {AuthValueProvider} from "@notAuthPages/auth/Providers/AuthValue.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    icons: {
      icon: [
          {
              url: '/svgs/favicon.svg',
              href: '/svgs/favicon.svg',
          }
      ]
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
        <ResponseProvider>
            <UserInfoProvider>
                <AuthValueProvider>
                    <body>
                    {children}
                    </body>
                </AuthValueProvider>
            </UserInfoProvider>
        </ResponseProvider>
    </html>
  );
}
